### ISSUE TITLE
An example app?

### ISSUE THREAD

**Issue by axhamre** [weslleyaraujo/redux-clipboard-copy#1]
This library looks amazing, but unfortunately I cannot get it to work (nothing gets copied to clipboard). It's most probably a usage problem on my part - it would be super useful to see a running app on codesandbox or stackblitz.

Thanks a lot! 😊

**Comment by weslleyaraujo** [comment]
hey! sorry the delay :(

Indeed there was a problem with the package main file.. but here we go:
https://codesandbox.io/s/l7p3yp184q

I will also add this demo at the readme, thanks for the feedback 🎉

**Comment by axhamre** [comment]
Wow!! 😀
